name: Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: install clang-format
        run: |
          sudo apt-get remove -y clang-6.0 libclang-common-6.0-dev libclang1-6.0 libllvm6.0
          sudo apt-get autoremove
          sudo apt-get install clang-format clang-format-6.0
      - uses: pre-commit/action@v2.0.0