name: Build and test wheels

on:
  push:
    branches:
      - master
      - test
  pull_request:
  create:

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]
        wordsize: [64]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install deps
        env:
          PYTHON: "py -${{ matrix.python }}-${{ matrix.wordsize }}"
        shell: bash
        run: |
          set -ex
          ${PYTHON} -m pip install --upgrade pip
          ${PYTHON} -m pip install setuptools wheel cython
#          ${PYTHON} -m pip install -r python/requirements/CI/wheel-build/requirements.txt
      - name: Build C extension
        env:
          PYTHON: "py -${{ matrix.python }}-${{ matrix.wordsize }}"
        shell: bash
        run: |
          set -ex
          # Fix symlinks on windows
          git config core.symlinks true
          git reset --hard
          cd python
          ${PYTHON} -VV
          ${PYTHON} setup.py build_ext --inplace
      - name: Build Wheel
        env:
          PYTHON: "py -${{ matrix.python }}-${{ matrix.wordsize }}"
        shell: bash
        run: |
          set -ex
          cd python
          ${PYTHON} setup.py bdist_wheel
      - name: Install wheel and run tests
        env:
          PYTHON: "py -${{ matrix.python }}-${{ matrix.wordsize }}"
        shell: bash
        run: |
          set -ex
          ${PYTHON} -m pip install -v kastore --only-binary :all: -f python/dist/ --no-index
          ${PYTHON} -c "import kastore"
          ${PYTHON} -m pip install -r python/requirements/CI/tests/requirements.txt
          rm -rf python/kastore python/*.so
          ${PYTHON} -m nose -v python
      - name: Upload Wheels
        uses: actions/upload-artifact@v1
        with:
          name: win-wheel-${{ matrix.python }}-${{ matrix.wordsize }}
          path: python/dist

  OSX:
    runs-on: macos-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install setuptools wheel
      - name: Build C extension
        run: |
          cd python
          python -VV
          python setup.py build_ext --inplace
      - name: Build Wheel
        run: |
          cd python
          python setup.py bdist_wheel
      - name: Install wheel and run tests
        run: |
          pip install -v kastore --only-binary :all: -f python/dist/ --no-index
          python -c "import kastore"
          pip install -r python/requirements/CI/tests/requirements.txt
          rm -rf python/kastore python/*.so
          python -m nose -v python
      - name: Upload Wheels
        uses: actions/upload-artifact@v1
        with:
          name: osx-wheel-${{ matrix.python }}
          path: python/dist

  manylinux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Build sdist
        shell: bash
        run: |
          cd python
          python setup.py sdist

      - name: Upload sdist
        uses: actions/upload-artifact@v1
        with:
          name: sdist
          path: python/dist

      - name: Build wheels in docker
        shell: bash
        run: |
          docker run --rm -v `pwd`:/project -w /project quay.io/pypa/manylinux2010_x86_64 bash docker/buildwheel.sh

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Run tests (3.8)
        run: |
          python -VV
          pip install -v kastore --only-binary :all: --no-index -f python/dist/wheelhouse
          python -c "import kastore"
          pip install -r python/requirements/CI/tests/requirements.txt
          python -m nose -v python

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Run tests (3.7)
        run: |
          python -VV
          pip install -v kastore --only-binary :all: --no-index -f python/dist/wheelhouse
          python -c "import kastore"
          pip install -r python/requirements/CI/tests/requirements.txt
          python -m nose -v python

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Run tests (3.6)
        run: |
          python -VV
          pip install -v kastore --only-binary :all: --no-index -f python/dist/wheelhouse
          python -c "import kastore"
          pip install -r python/requirements/CI/tests/requirements.txt
          python -m nose -v python

      - name: Upload Wheels
        uses: actions/upload-artifact@v1
        with:
          name: linux-wheels
          path: python/dist/wheelhouse